import { Command } from "commander";
import chalk from "chalk";
import { writeFile, readFile } from "node:fs/promises";
import { join } from "node:path";
import { loadConfig } from "../config.js";
import { scanProject } from "../scan.js";
import { parseJavaFiles, ParsedDecl, ParsedField, ParsedTool } from "../classTree.js";

interface ScaffoldOpts {
  output?: string;
}

const DEFAULT_OUTPUT = "confiqure.tools.ts";

export function registerScaffold(program: Command): void {
  program
    .command("scaffold")
    .description("Generate frontend-tool handler stubs (confiqure.tools.ts) from @Confiqure.Tool(serverSide=false) methods")
    .option("-o, --output <file>", "output file path", DEFAULT_OUTPUT)
    .action(async (opts: ScaffoldOpts) => {
      const cwd = process.cwd();
      const config = await loadConfig(cwd);
      const scan = await scanProject(cwd, config);

      const frontendTools = scan.tools.filter((t) => !t.serverSide);
      if (frontendTools.length === 0) {
        console.log(chalk.dim("No frontend tools (@Confiqure.Tool serverSide=false) found — nothing to scaffold."));
        return;
      }

      // Build a project DTO index so we can generate matching TS interfaces.
      const javaFiles = new Map<string, string>();
      for (const [p, content] of scan.allFiles) {
        if (p.endsWith(".java")) javaFiles.set(p, content);
      }
      const parsed = await parseJavaFiles(javaFiles);
      const declIndex = new Map<string, ParsedDecl>();
      for (const pf of parsed) {
        for (const decl of pf.declarations) {
          if (!declIndex.has(decl.name)) declIndex.set(decl.name, decl);
        }
      }

      const generated = generateModule(frontendTools, declIndex);

      const outPath = join(cwd, opts.output ?? DEFAULT_OUTPUT);
      const existing = await readFile(outPath, "utf8").catch(() => null);

      if (existing == null) {
        await writeFile(outPath, generated.full, "utf8");
        console.log(chalk.green("✓"), `Wrote ${opts.output ?? DEFAULT_OUTPUT} with ${frontendTools.length} handler stub${frontendTools.length === 1 ? "" : "s"}.`);
        console.log(chalk.dim("  Implement each handler body, then pass the object to confiqure.init({ tools })."));
        return;
      }

      // Merge-safe: never clobber an existing file. Report only the missing stubs.
      const missing = frontendTools.filter((t) => !existing.includes(`${t.name}:`));
      if (missing.length === 0) {
        console.log(chalk.green("✓"), `${opts.output ?? DEFAULT_OUTPUT} already has handlers for all ${frontendTools.length} frontend tool${frontendTools.length === 1 ? "" : "s"}.`);
        return;
      }
      console.log(
        chalk.yellow("⚠"),
        `${opts.output ?? DEFAULT_OUTPUT} exists. Add ${missing.length} missing handler${missing.length === 1 ? "" : "s"} below (not written to avoid clobbering your code):`
      );
      console.log();
      console.log(generateStubs(missing));
    });
}

interface GeneratedModule {
  full: string;
}

function generateModule(tools: ParsedTool[], declIndex: Map<string, ParsedDecl>): GeneratedModule {
  // Generate interfaces for every project DTO reachable from a tool's input type.
  const wantTypes = new Set<string>();
  for (const t of tools) {
    if (t.inputType) collectProjectTypes(t.inputType, declIndex, wantTypes);
  }
  const interfaces: string[] = [];
  for (const typeName of wantTypes) {
    const decl = declIndex.get(typeName);
    if (decl) interfaces.push(renderInterface(decl, declIndex));
  }

  const header =
    `// AUTO-GENERATED by \`confiqure scaffold\`. Implement the handler bodies.\n` +
    `// Safe to re-run: existing files are never overwritten (missing stubs are printed instead).\n` +
    `// Pass this object to confiqure.init({ tools }).\n`;

  const ctxType =
    `export interface ConfiqureToolContext {\n` +
    `  input: unknown\n` +
    `  endUserHandle?: string\n` +
    `  conversationId: number\n` +
    `  workspaceKey: string\n` +
    `  progress: (message: string) => void\n` +
    `  signal: AbortSignal\n` +
    `}\n`;

  const body = [header, ctxType, ...interfaces, generateStubs(tools)].filter((s) => s.length > 0).join("\n");
  return { full: body.endsWith("\n") ? body : body + "\n" };
}

function generateStubs(tools: ParsedTool[]): string {
  const lines: string[] = ["export const tools = {"];
  tools.forEach((t, i) => {
    const inputTs = t.inputType ? javaTypeToTs(t.inputType) : "unknown";
    const ret = t.returnType && t.returnType !== "void" ? javaTypeToTs(t.returnType) : "void";
    const docLines = docComment(t, inputTs, ret);
    lines.push(...docLines.map((l) => "  " + l));
    lines.push(`  ${t.name}: async (input: ${inputTs}, ctx: ConfiqureToolContext): Promise<${ret === "void" ? "void" : ret}> => {`);
    lines.push(`    // TODO: implement ${t.name}`);
    lines.push(`    throw new Error("${t.name} not implemented");`);
    lines.push(`  }${i === tools.length - 1 ? "" : ","}`);
  });
  lines.push("}");
  return lines.join("\n");
}

function docComment(t: ParsedTool, inputTs: string, ret: string): string[] {
  const out: string[] = ["/**"];
  const desc = cleanDoc(t.doc);
  if (desc) out.push(` * ${desc}`);
  out.push(` * @param input ${inputTs}`);
  out.push(` * @returns ${ret}`);
  out.push(" */");
  return out;
}

function cleanDoc(doc: string | null): string {
  if (!doc) return "";
  return doc
    .replace(/\/\*\*?|\*\//g, "")
    .replace(/^\s*\*/gm, "")
    .replace(/@confiqure\b.*$/gim, "")
    .split("\n")
    .map((l) => l.trim())
    .filter((l) => l.length > 0)
    .join(" ")
    .slice(0, 300);
}

/** Walk a Java input type and collect project DTO names reachable via fields. */
function collectProjectTypes(typeText: string, declIndex: Map<string, ParsedDecl>, out: Set<string>): void {
  for (const base of baseTypeNames(typeText)) {
    const decl = declIndex.get(base);
    if (!decl || out.has(base)) continue;
    if (decl.kind === "enum" || decl.kind === "interface") {
      out.add(base); // still emit a (string-ish) interface for records/classes only
    }
    if (decl.kind === "class" || decl.kind === "record") {
      out.add(base);
      for (const f of decl.fields) {
        collectProjectTypes(f.typeText, declIndex, out);
      }
    }
  }
}

function renderInterface(decl: ParsedDecl, declIndex: Map<string, ParsedDecl>): string {
  if (decl.kind === "enum") {
    return `export type ${decl.name} = string\n`;
  }
  const lines: string[] = [`export interface ${decl.name} {`];
  for (const f of decl.fields) {
    lines.push(`  ${f.name}: ${javaTypeToTs(f.typeText)}`);
  }
  lines.push("}");
  return lines.join("\n") + "\n";
}

const JAVA_SCALAR_TO_TS: Record<string, string> = {
  String: "string", char: "string", Character: "string", CharSequence: "string", UUID: "string",
  int: "number", Integer: "number", long: "number", Long: "number",
  double: "number", Double: "number", float: "number", Float: "number",
  short: "number", Short: "number", byte: "number", Byte: "number",
  BigDecimal: "number", BigInteger: "number",
  boolean: "boolean", Boolean: "boolean",
  LocalDate: "string", LocalDateTime: "string", LocalTime: "string", Instant: "string",
  OffsetDateTime: "string", ZonedDateTime: "string", Date: "string",
  Object: "unknown",
};

/** Best-effort Java type expression -> TypeScript type. */
function javaTypeToTs(typeText: string): string {
  const t = typeText.trim();

  if (t.endsWith("[]")) return `${javaTypeToTs(t.slice(0, -2))}[]`;

  const generic = t.match(/^([A-Za-z0-9_.]+)\s*<(.+)>$/);
  if (generic) {
    const base = lastSeg(generic[1]);
    const args = splitGenericArgs(generic[2]);
    if (["List", "Set", "Collection", "Iterable", "ArrayList", "HashSet"].includes(base)) {
      return `${javaTypeToTs(args[0] ?? "Object")}[]`;
    }
    if (["Map", "HashMap", "LinkedHashMap"].includes(base)) {
      const val = args[1] ?? "Object";
      return `Record<string, ${javaTypeToTs(val)}>`;
    }
    if (base === "Optional") return `${javaTypeToTs(args[0] ?? "Object")} | null`;
    return "unknown";
  }

  const base = lastSeg(t);
  if (JAVA_SCALAR_TO_TS[base]) return JAVA_SCALAR_TO_TS[base];
  // Unknown reference type — assume a project DTO/enum interface of the same name.
  if (/^[A-Z]/.test(base)) return base;
  return "unknown";
}

function baseTypeNames(typeText: string): string[] {
  const out: string[] = [];
  const visit = (s: string) => {
    const t = s.trim().replace(/\[\]$/, "");
    const generic = t.match(/^([A-Za-z0-9_.]+)\s*<(.+)>$/);
    if (generic) {
      out.push(lastSeg(generic[1]));
      for (const a of splitGenericArgs(generic[2])) visit(a);
    } else {
      out.push(lastSeg(t));
    }
  };
  visit(typeText);
  return out;
}

function splitGenericArgs(s: string): string[] {
  const args: string[] = [];
  let depth = 0;
  let cur = "";
  for (const ch of s) {
    if (ch === "<") depth++;
    if (ch === ">") depth--;
    if (ch === "," && depth === 0) {
      args.push(cur.trim());
      cur = "";
    } else {
      cur += ch;
    }
  }
  if (cur.trim()) args.push(cur.trim());
  return args;
}

function lastSeg(name: string): string {
  const dot = name.lastIndexOf(".");
  return dot === -1 ? name : name.slice(dot + 1);
}
